version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python3 init_db.py && python3 app/main.py"
    ports:
      - "8080:8080"
    depends_on:
      - db
